### ISSUE TITLE
Kubernetes - Cluster max memory/cpu

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control-registry#237]

**Comment by yashmehrotra** [comment]
@moshloop 

Pretty hard to do this since there would be different lookups for usage and max, since pods and nodes are created dynamically, we can merge the properties with max coming from pod object and value coming from a check

I remember we thought of doing this: https://github.com/flanksource/canary-checker/issues/1378 to solve these kind of scenarios

Is there any other way we can approach this ?
